# Use a imagem oficial do Python como imagem base
FROM python:3.9

# Defina o diretório de trabalho dentro do container
WORKDIR /app

# Copie o arquivo requirements.txt para o diretório de trabalho
COPY requirements.txt .

# Instale as dependências do Flask
RUN pip install --no-cache-dir -r requirements.txt

# Copie o restante dos arquivos da aplicação para o diretório de trabalho
COPY . .

# Exponha a porta 5000 para o Flask
EXPOSE 5000

# Comando para iniciar o Flask quando o container for executado
CMD ["python", "main.py"]
